name: $(version)

#TODO: Change version.major to 21 once pipeline is ready to be enabled 
variables:
  version.major: 99
  version.minor: 0
  version.update: 0
  version.phase: a
  version.name: $[format('{0}.{1}.{2}.{3}', variables['version.major'], variables['version.minor'], variables['version.update'], variables['version.phase'])]
  version.revision: $[counter(variables['version.name'], 0)]
  version: $[format('{0}{1}', variables['version.name'], variables['version.revision'])]
  buildsdk: ${{parameters.buildsdk}}
  buildfeed: ${{parameters.buildfeed}}

parameters:
  - name: buildsdk
    displayName: Build SDK?
    type: boolean
    default: false
  - name: buildfeed
    displayName: Build package feed?
    type: boolean
    default: false

trigger:
- main

resources:
  repositories:
  - repository: smartracks-script
    type: github
    name: ni/smartracks-script
    ref: refs/heads/main
    endpoint: smartracks
  - repository: rcu-service
    type: github
    name: ni/rcu-service
    ref: refs/heads/main
    endpoint: smartracks
  - repository: smartracks-manifest
    type: github
    name: ni/smartracks-manifest
    ref: refs/heads/main
    endpoint: smartracks
  - repository: meta-smartracks
    type: github
    name: ni/meta-smartracks
    ref: refs/heads/main
    endpoint: smartracks
  containers:
  - container: smartracks-build
    image: rnd-builds.repos.natinst.com/smartracks/smartracks-build:0.3
    options:
    volumes:
    - /mnt:/mnt
         
jobs:
 - template: azure-pipeline-template/ci.yml@smartracks-script
