trigger:
- main

resources:
  repositories:
  - repository: smartracks-script
    type: github
    name: ni/smartracks-script
    ref: refs/heads/main
    endpoint: smartracks
  - repository: rcu-service
    type: github
    name: ni/rcu-service
    ref: refs/heads/main
    endpoint: smartracks
  - repository: smartracks-manifest
    type: github
    name: ni/smartracks-manifest
    ref: refs/heads/main
    endpoint: smartracks
  - repository: meta-smartracks
    type: github
    name: ni/meta-smartracks
    ref: refs/heads/main
    endpoint: smartracks
  containers:
  - container: smartracks-build
    image: rnd-builds.repos.natinst.com/smartracks/smartracks-build:0.3
    options:
    volumes:
    - /mnt:/mnt
         
jobs:
 - template: azure-pipeline-template/ci.yml@smartracks-script
