# Stub pipeline
# Updates the TriggeringPipeline variable in SmartRacksPipelineVariables group.
# After execution of this pipeline is finished, rcu-image-ci-pipeline.yml located in smatracks-script should be executed.

variables:
  - group: SmartRacksPipelineVariables

trigger:
- main

pr: none

pool:
  name: Drivers-NIBuildFarm-RFMIBUILD

steps:
- script: echo Triggering rcu-image-ci-pipeline!
- powershell: |
    $url = "https://dev.azure.com/ni/DevCentral/_apis/distributedtask/variablegroups/303?api-version=5.0-preview.1"
    $json = '{"id":2,"type":"Vsts","name":"SmartRacksPipelineVariables","variables":{"TriggeringPipeline":{"isSecret":false,"value":"smartracks-manifest"},"CommitMessage":{"isSecret":false,"value":"$(Build.SourceVersionMessage)"}}}'
    $pipeline = Invoke-RestMethod -Uri $url -Method Put -Body $json -ContentType "application/json" -Headers @{
        Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN"
    }
    Write-Host "New Variable Value:" $pipeline.variables.TriggeringPipeline.value
  env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
